site_name: l-LCL-l--Y3zYnC-CnYz3Y2m1l3--l-LCL-l
repo_url: https://github.com/statesflowwishes-sketch/l-LCL-l--Y3zYnC-CnYz3Y2m1l3--l-LCL-l
nav:
  - Start: docs/index.md
  - Regelwerk: docs/REGELWERK.md
  - Evidenzen: docs/EVIDENZEN.md
  - Architektur: docs/ARCHITEKTUR.md
  - Risiken: docs/RISIKEN.md
theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - content.code.copy
    - content.tabs.link
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - toc:
      permalink: true
plugins:
  - search
  - glightbox
  - mermaid2
  - awesome-pages
  - table-reader
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/statesflowwishes-sketch/l-LCL-l--Y3zYnC-CnYz3Y2m1l3--l-LCL-l
